
title: "my first blog"
date: 2021-10-01


author: selam
email: your-email@domain.com
description: > # this means to ignore newlines until "baseurl:"
  this is my first site it is all about creating a gitup sestion and i am excited to learn.
  
# social links
twitter_username: your-twitter-handle # DO NOT include the @ character, or else the build will fail!
github_username:  your-github-handle # DO NOT include the @ character, or else the build will fail!

show_excerpts: true # set to false to remove excerpts on the homepage
theme: minima
